"""Tests for Alembic schema migrations and autogenerate drift checks."""

from pathlib import Path
import os
import pytest
from alembic.config import Config
from alembic import command
from sqlalchemy import create_engine, inspect

from adam.db.models import Base


def test_alembic_upgrade_head_on_fresh_database(tmp_path):
    """Verify that a fresh database successfully migrates to head via Alembic without errors."""
    db_file = tmp_path / "fresh_migration.db"
    db_url = f"sqlite:///{db_file}"

    repo_root = Path(__file__).resolve().parent.parent
    alembic_ini = repo_root / "alembic.ini"
    assert alembic_ini.is_file(), f"alembic.ini not found at {alembic_ini}"

    alembic_cfg = Config(str(alembic_ini))
    alembic_cfg.set_main_option("sqlalchemy.url", db_url)

    # 1. Run migrations to head
    command.upgrade(alembic_cfg, "head")

    # 2. Inspect created tables
    engine = create_engine(db_url)
    inspector = inspect(engine)
    tables = set(inspector.get_table_names())
    engine.dispose()

    # Verify core tables are present
    assert "documents" in tables
    assert "sources" in tables
    assert "document_versions" in tables
    assert "document_chunks" in tables
    assert "users" in tables
    assert "audit_events" in tables
    assert "alembic_version" in tables

    # Verify at least 30 tables were created
    assert len(tables) >= 30


def test_alembic_check_no_drift(tmp_path):
    """Verify that alembic check detects zero schema drift against current SQLAlchemy models."""
    db_file = tmp_path / "check_drift.db"
    db_url = f"sqlite:///{db_file}"

    repo_root = Path(__file__).resolve().parent.parent
    alembic_ini = repo_root / "alembic.ini"
    alembic_cfg = Config(str(alembic_ini))
    alembic_cfg.set_main_option("sqlalchemy.url", db_url)

    # Upgrade to head first
    command.upgrade(alembic_cfg, "head")

    # Run alembic check (raises AutogenerateDiffsDetected if schema and models drift)
    command.check(alembic_cfg)
