"""baseline_schema

Revision ID: 6739c00670e4
Revises: 
Create Date: 2026-10-01 03:39:32.831607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy.vector


# revision identifiers, used by Alembic.
revision: str = '6739c00670e4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_execution_audits',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('user_role', sa.String(length=64), nullable=False),
    sa.Column('department_id', sa.String(length=64), nullable=True),
    sa.Column('clearance_level', sa.String(length=32), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('detected_intent', sa.String(length=64), nullable=True),
    sa.Column('model_id', sa.String(length=64), nullable=True),
    sa.Column('retrieval_pass_count', sa.Integer(), nullable=False),
    sa.Column('answer_pass_count', sa.Integer(), nullable=False),
    sa.Column('is_no_answer', sa.Integer(), nullable=False),
    sa.Column('is_high_risk', sa.Integer(), nullable=False),
    sa.Column('state_transitions_json', sa.JSON(), nullable=False),
    sa.Column('tool_calls_json', sa.JSON(), nullable=False),
    sa.Column('validation_passed', sa.Integer(), nullable=False),
    sa.Column('validation_errors_json', sa.JSON(), nullable=True),
    sa.Column('currency_banners_json', sa.JSON(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('memory_used_mb', sa.Float(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('temperature_applied', sa.Float(), nullable=False),
    sa.Column('redacted_audit_log', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_agent_date', 'agent_execution_audits', ['created_at'], unique=False)
    op.create_index('idx_agent_session', 'agent_execution_audits', ['session_id'], unique=False)
    op.create_index('idx_agent_user', 'agent_execution_audits', ['user_id'], unique=False)
    op.create_index(op.f('ix_agent_execution_audits_session_id'), 'agent_execution_audits', ['session_id'], unique=False)
    op.create_table('answer_reconstruction_audits',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('trace_id', sa.String(length=64), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('model_id', sa.String(length=64), nullable=False),
    sa.Column('model_revision', sa.String(length=64), nullable=True),
    sa.Column('prompt_version', sa.String(length=64), nullable=False),
    sa.Column('index_version_ids', sa.JSON(), nullable=False),
    sa.Column('cited_chunk_ids', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_recon_req_hash', 'answer_reconstruction_audits', ['request_hash'], unique=False)
    op.create_index('idx_recon_trace', 'answer_reconstruction_audits', ['trace_id'], unique=False)
    op.create_index(op.f('ix_answer_reconstruction_audits_request_hash'), 'answer_reconstruction_audits', ['request_hash'], unique=False)
    op.create_index(op.f('ix_answer_reconstruction_audits_session_id'), 'answer_reconstruction_audits', ['session_id'], unique=False)
    op.create_index(op.f('ix_answer_reconstruction_audits_trace_id'), 'answer_reconstruction_audits', ['trace_id'], unique=False)
    op.create_index(op.f('ix_answer_reconstruction_audits_user_id'), 'answer_reconstruction_audits', ['user_id'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('sequence_num', sa.BigInteger(), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('actor', sa.String(length=128), nullable=False),
    sa.Column('details_json', sa.JSON(), nullable=True),
    sa.Column('prev_hash', sa.String(length=64), nullable=True),
    sa.Column('entry_hash', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_entity', 'audit_events', ['entity_type', 'entity_id'], unique=False)
    op.create_index('idx_audit_seq', 'audit_events', ['sequence_num'], unique=False)
    op.create_index('idx_audit_timestamp', 'audit_events', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_events_sequence_num'), 'audit_events', ['sequence_num'], unique=False)
    op.create_table('chat_sessions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('classification_ceiling', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_chat_user_exp', 'chat_sessions', ['user_id', 'expires_at'], unique=False)
    op.create_index(op.f('ix_chat_sessions_expires_at'), 'chat_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_chat_sessions_user_id'), 'chat_sessions', ['user_id'], unique=False)
    op.create_table('feedback_records',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('trace_id', sa.String(length=64), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('feedback_type', sa.String(length=64), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('correction_text', sa.Text(), nullable=True),
    sa.Column('cited_chunk_ids', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_feedback_trace', 'feedback_records', ['trace_id'], unique=False)
    op.create_index('idx_feedback_user', 'feedback_records', ['user_id'], unique=False)
    op.create_index(op.f('ix_feedback_records_session_id'), 'feedback_records', ['session_id'], unique=False)
    op.create_index(op.f('ix_feedback_records_trace_id'), 'feedback_records', ['trace_id'], unique=False)
    op.create_index(op.f('ix_feedback_records_user_id'), 'feedback_records', ['user_id'], unique=False)
    op.create_table('idempotency_records',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('endpoint', sa.String(length=128), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=False),
    sa.Column('response_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_idempotency_records_expires_at'), 'idempotency_records', ['expires_at'], unique=False)
    op.create_index(op.f('ix_idempotency_records_user_id'), 'idempotency_records', ['user_id'], unique=False)
    op.create_table('model_artifacts',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('revision', sa.String(length=64), nullable=False),
    sa.Column('quantization', sa.String(length=32), nullable=False),
    sa.Column('model_format', sa.String(length=32), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('license_id', sa.String(length=64), nullable=False),
    sa.Column('license_status', sa.String(length=32), nullable=False),
    sa.Column('context_window', sa.Integer(), nullable=False),
    sa.Column('serving_runtime', sa.String(length=64), nullable=False),
    sa.Column('prompt_template', sa.Text(), nullable=False),
    sa.Column('is_primary', sa.Integer(), nullable=False),
    sa.Column('is_fallback', sa.Integer(), nullable=False),
    sa.Column('is_comparator', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('sbom_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_model_checksum', 'model_artifacts', ['checksum_sha256'], unique=False)
    op.create_index('idx_model_name_rev', 'model_artifacts', ['name', 'revision'], unique=False)
    op.create_table('organizations',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('rag_triad_benchmarks',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('model_id', sa.String(length=128), nullable=False),
    sa.Column('trigger_event', sa.String(length=64), nullable=False),
    sa.Column('total_queries', sa.Integer(), nullable=False),
    sa.Column('passed_queries', sa.Integer(), nullable=False),
    sa.Column('context_relevance', sa.Float(), nullable=False),
    sa.Column('groundedness', sa.Float(), nullable=False),
    sa.Column('answer_relevance', sa.Float(), nullable=False),
    sa.Column('composite_score', sa.Float(), nullable=False),
    sa.Column('zero_hallucination_rate', sa.Float(), nullable=False),
    sa.Column('drift_detected', sa.Boolean(), nullable=False),
    sa.Column('drift_notes_json', sa.JSON(), nullable=True),
    sa.Column('department_scores_json', sa.JSON(), nullable=True),
    sa.Column('language_scores_json', sa.JSON(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rag_triad_benchmarks_model_id'), 'rag_triad_benchmarks', ['model_id'], unique=False)
    op.create_table('sources',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('department_id', sa.String(length=64), nullable=False),
    sa.Column('owner_name', sa.String(length=255), nullable=False),
    sa.Column('owner_contact', sa.String(length=255), nullable=False),
    sa.Column('written_authority_ref', sa.String(length=255), nullable=False),
    sa.Column('permitted_domains', sa.JSON(), nullable=False),
    sa.Column('permitted_path_prefixes', sa.JSON(), nullable=False),
    sa.Column('access_classification', sa.String(length=32), nullable=False),
    sa.Column('refresh_cadence', sa.String(length=32), nullable=False),
    sa.Column('rate_limit_per_minute', sa.Integer(), nullable=False),
    sa.Column('retention_policy', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_run_status', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_preferences',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('opt_in', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.String(length=255), nullable=True),
    sa.Column('preference_data_ciphertext', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_preferences_user_id'), 'user_preferences', ['user_id'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('department_id', sa.String(length=64), nullable=False),
    sa.Column('clearance_level', sa.String(length=32), nullable=False),
    sa.Column('roles_json', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('api_keys',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('roles_json', sa.JSON(), nullable=False),
    sa.Column('clearance_level', sa.String(length=32), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=True)
    op.create_index(op.f('ix_api_keys_user_id'), 'api_keys', ['user_id'], unique=False)
    op.create_table('chat_turns',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('content_ciphertext', sa.Text(), nullable=False),
    sa.Column('cited_chunk_ids', sa.JSON(), nullable=True),
    sa.Column('retention_tag', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_turn_session_time', 'chat_turns', ['session_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_chat_turns_session_id'), 'chat_turns', ['session_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=True),
    sa.Column('department_id', sa.String(length=64), nullable=False),
    sa.Column('doc_type', sa.String(length=64), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('authority_level', sa.String(length=64), nullable=False),
    sa.Column('classification', sa.String(length=32), nullable=False),
    sa.Column('current_version_id', sa.String(length=64), nullable=True),
    sa.Column('lifecycle_status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingestion_jobs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('job_type', sa.String(length=32), nullable=False),
    sa.Column('current_stage', sa.String(length=64), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('trace_id', sa.String(length=64), nullable=True),
    sa.Column('collector_version', sa.String(length=32), nullable=False),
    sa.Column('count_found', sa.Integer(), nullable=False),
    sa.Column('count_ingested', sa.Integer(), nullable=False),
    sa.Column('count_skipped', sa.Integer(), nullable=False),
    sa.Column('count_failed', sa.Integer(), nullable=False),
    sa.Column('progress_pct', sa.Float(), nullable=False),
    sa.Column('checkpoint_json', sa.JSON(), nullable=True),
    sa.Column('failures_json', sa.JSON(), nullable=True),
    sa.Column('metrics_json', sa.JSON(), nullable=True),
    sa.Column('cancel_requested', sa.Boolean(), nullable=False),
    sa.Column('pause_requested', sa.Boolean(), nullable=False),
    sa.Column('parent_job_id', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_job_id'], ['ingestion_jobs.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_jobs_idempotency_key'), 'ingestion_jobs', ['idempotency_key'], unique=False)
    op.create_index(op.f('ix_ingestion_jobs_source_id'), 'ingestion_jobs', ['source_id'], unique=False)
    op.create_index(op.f('ix_ingestion_jobs_trace_id'), 'ingestion_jobs', ['trace_id'], unique=False)
    op.create_table('ingestion_runs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('collector_version', sa.String(length=32), nullable=False),
    sa.Column('count_found', sa.Integer(), nullable=False),
    sa.Column('count_downloaded', sa.Integer(), nullable=False),
    sa.Column('failures_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('memberships',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memberships_organization_id'), 'memberships', ['organization_id'], unique=False)
    op.create_index(op.f('ix_memberships_user_id'), 'memberships', ['user_id'], unique=False)
    op.create_table('model_promotions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('model_id', sa.String(length=64), nullable=False),
    sa.Column('promoted_by', sa.String(length=128), nullable=False),
    sa.Column('authority_order_ref', sa.String(length=255), nullable=False),
    sa.Column('gold_set_passed', sa.Integer(), nullable=False),
    sa.Column('recall_at_10', sa.Float(), nullable=True),
    sa.Column('page_precision', sa.Float(), nullable=True),
    sa.Column('no_answer_refusal_rate', sa.Float(), nullable=True),
    sa.Column('acl_leak_count', sa.Integer(), nullable=False),
    sa.Column('hindi_review_passed', sa.Integer(), nullable=False),
    sa.Column('hindi_review_notes', sa.Text(), nullable=True),
    sa.Column('latency_p95_ms', sa.Float(), nullable=True),
    sa.Column('peak_memory_mb', sa.Float(), nullable=True),
    sa.Column('unanswerable_abstention_rate', sa.Float(), nullable=True),
    sa.Column('high_risk_compliance_rate', sa.Float(), nullable=True),
    sa.Column('license_approved', sa.Integer(), nullable=False),
    sa.Column('decision', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('promoted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['model_artifacts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_prom_date', 'model_promotions', ['promoted_at'], unique=False)
    op.create_index('idx_prom_model', 'model_promotions', ['model_id'], unique=False)
    op.create_table('session_summaries',
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('summary_ciphertext', sa.Text(), nullable=False),
    sa.Column('source_turn_ids', sa.JSON(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_session_summaries_expires_at'), 'session_summaries', ['expires_at'], unique=False)
    op.create_table('access_grants',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('subject_id', sa.String(length=128), nullable=False),
    sa.Column('document_id', sa.String(length=64), nullable=True),
    sa.Column('classification', sa.String(length=32), nullable=True),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('granted_by', sa.String(length=128), nullable=True),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_versions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('document_id', sa.String(length=64), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('source_locator', sa.Text(), nullable=True),
    sa.Column('issued_on', sa.Date(), nullable=True),
    sa.Column('published_on', sa.Date(), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('go_number', sa.String(length=128), nullable=True),
    sa.Column('gazette_number', sa.String(length=128), nullable=True),
    sa.Column('supersedes_version_id', sa.String(length=64), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=False),
    sa.Column('byte_size', sa.BigInteger(), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('provenance_status', sa.String(length=32), nullable=False),
    sa.Column('license_id', sa.String(length=64), nullable=True),
    sa.Column('original_object_key', sa.Text(), nullable=False),
    sa.Column('http_headers', sa.JSON(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supersedes_version_id'], ['document_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_doc_ver_document_id', 'document_versions', ['document_id'], unique=False)
    op.create_index('idx_doc_ver_retrieved_at', 'document_versions', ['retrieved_at'], unique=False)
    op.create_index('idx_doc_ver_sha256', 'document_versions', ['sha256'], unique=False)
    op.create_index('idx_doc_ver_source_url', 'document_versions', ['source_url'], unique=False)
    op.create_index(op.f('ix_document_versions_sha256'), 'document_versions', ['sha256'], unique=False)
    op.create_table('document_attributes',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('version_id', sa.String(length=64), nullable=False),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('issuing_authority_title', sa.String(length=255), nullable=True),
    sa.Column('signatory_name', sa.String(length=255), nullable=True),
    sa.Column('department_hierarchy', sa.JSON(), nullable=True),
    sa.Column('order_number', sa.String(length=128), nullable=True),
    sa.Column('order_date', sa.Date(), nullable=True),
    sa.Column('language_distribution', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['document_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_id')
    )
    op.create_index(op.f('ix_document_attributes_order_number'), 'document_attributes', ['order_number'], unique=False)
    op.create_table('document_chunks',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('document_id', sa.String(length=64), nullable=False),
    sa.Column('version_id', sa.String(length=64), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('page_start', sa.Integer(), nullable=False),
    sa.Column('page_end', sa.Integer(), nullable=False),
    sa.Column('section_heading', sa.String(length=255), nullable=True),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('department_id', sa.String(length=64), nullable=False),
    sa.Column('doc_type', sa.String(length=64), nullable=False),
    sa.Column('classification', sa.String(length=32), nullable=False),
    sa.Column('authority', sa.String(length=255), nullable=True),
    sa.Column('order_date', sa.Date(), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('go_number', sa.String(length=128), nullable=True),
    sa.Column('gazette_number', sa.String(length=128), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('review_status', sa.String(length=32), nullable=False),
    sa.Column('block_ids_json', sa.JSON(), nullable=True),
    sa.Column('bbox_list_json', sa.JSON(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=128), nullable=True),
    sa.Column('embedding_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['document_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_chunk_dept_class', 'document_chunks', ['department_id', 'classification'], unique=False)
    op.create_index('idx_chunk_document_id', 'document_chunks', ['document_id'], unique=False)
    op.create_index('idx_chunk_embedding_hnsw', 'document_chunks', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('idx_chunk_go_num', 'document_chunks', ['go_number'], unique=False)
    op.create_index('idx_chunk_review_dept_class', 'document_chunks', ['review_status', 'department_id', 'classification'], unique=False)
    op.create_index('idx_chunk_version_idx', 'document_chunks', ['version_id', 'chunk_index'], unique=False)
    op.create_index(op.f('ix_document_chunks_go_number'), 'document_chunks', ['go_number'], unique=False)
    op.create_table('document_pages',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('version_id', sa.String(length=64), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('clean_text', sa.Text(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('is_scanned', sa.Integer(), nullable=False),
    sa.Column('scan_quality_score', sa.Integer(), nullable=True),
    sa.Column('detected_language', sa.String(length=16), nullable=False),
    sa.Column('tables_json', sa.JSON(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('image_key', sa.Text(), nullable=True),
    sa.Column('ocr_text', sa.Text(), nullable=False),
    sa.Column('selected_text', sa.Text(), nullable=False),
    sa.Column('text_confidence', sa.Float(), nullable=True),
    sa.Column('rotation', sa.Integer(), nullable=False),
    sa.Column('review_status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['document_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_page_ver_num', 'document_pages', ['version_id', 'page_number'], unique=False)
    op.create_index('idx_page_version_id', 'document_pages', ['version_id'], unique=False)
    op.create_table('ingestion_job_items',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('job_id', sa.String(length=64), nullable=False),
    sa.Column('item_key', sa.String(length=512), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('document_id', sa.String(length=64), nullable=True),
    sa.Column('version_id', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['ingestion_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['document_versions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_job_items_item_key'), 'ingestion_job_items', ['item_key'], unique=False)
    op.create_index(op.f('ix_ingestion_job_items_job_id'), 'ingestion_job_items', ['job_id'], unique=False)
    op.create_index(op.f('ix_ingestion_job_items_sha256'), 'ingestion_job_items', ['sha256'], unique=False)
    op.create_index(op.f('ix_ingestion_job_items_status'), 'ingestion_job_items', ['status'], unique=False)
    op.create_table('precedent_references',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('source_version_id', sa.String(length=64), nullable=False),
    sa.Column('raw_citation_text', sa.Text(), nullable=False),
    sa.Column('cited_order_number', sa.String(length=128), nullable=True),
    sa.Column('cited_date', sa.Date(), nullable=True),
    sa.Column('cited_act_or_rule', sa.String(length=255), nullable=True),
    sa.Column('target_document_id', sa.String(length=64), nullable=True),
    sa.Column('relation_type', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_version_id'], ['document_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_prec_source_version', 'precedent_references', ['source_version_id'], unique=False)
    op.create_index(op.f('ix_precedent_references_cited_order_number'), 'precedent_references', ['cited_order_number'], unique=False)
    op.create_table('processing_runs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('version_id', sa.String(length=64), nullable=False),
    sa.Column('parser_version', sa.String(length=32), nullable=False),
    sa.Column('ocr_engine', sa.String(length=64), nullable=True),
    sa.Column('model_version', sa.String(length=64), nullable=True),
    sa.Column('config_hash', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result', sa.String(length=32), nullable=False),
    sa.Column('details_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['version_id'], ['document_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_prun_version', 'processing_runs', ['version_id'], unique=False)
    op.create_table('extracted_tables',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('page_id', sa.String(length=64), nullable=False),
    sa.Column('html_or_csv_key', sa.Text(), nullable=True),
    sa.Column('bbox', sa.JSON(), nullable=True),
    sa.Column('extraction_method', sa.String(length=32), nullable=False),
    sa.Column('review_status', sa.String(length=32), nullable=False),
    sa.Column('table_data_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['document_pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review_annotations',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('page_id', sa.String(length=64), nullable=False),
    sa.Column('reviewer', sa.String(length=128), nullable=False),
    sa.Column('corrected_text', sa.Text(), nullable=False),
    sa.Column('annotation_type', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['document_pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('text_blocks',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('page_id', sa.String(length=64), nullable=False),
    sa.Column('block_type', sa.String(length=32), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('bbox', sa.JSON(), nullable=True),
    sa.Column('reading_order', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['page_id'], ['document_pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_block_page', 'text_blocks', ['page_id', 'reading_order'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_block_page', table_name='text_blocks')
    op.drop_table('text_blocks')
    op.drop_table('review_annotations')
    op.drop_table('extracted_tables')
    op.drop_index('idx_prun_version', table_name='processing_runs')
    op.drop_table('processing_runs')
    op.drop_index(op.f('ix_precedent_references_cited_order_number'), table_name='precedent_references')
    op.drop_index('idx_prec_source_version', table_name='precedent_references')
    op.drop_table('precedent_references')
    op.drop_index(op.f('ix_ingestion_job_items_status'), table_name='ingestion_job_items')
    op.drop_index(op.f('ix_ingestion_job_items_sha256'), table_name='ingestion_job_items')
    op.drop_index(op.f('ix_ingestion_job_items_job_id'), table_name='ingestion_job_items')
    op.drop_index(op.f('ix_ingestion_job_items_item_key'), table_name='ingestion_job_items')
    op.drop_table('ingestion_job_items')
    op.drop_index('idx_page_version_id', table_name='document_pages')
    op.drop_index('idx_page_ver_num', table_name='document_pages')
    op.drop_table('document_pages')
    op.drop_index(op.f('ix_document_chunks_go_number'), table_name='document_chunks')
    op.drop_index('idx_chunk_version_idx', table_name='document_chunks')
    op.drop_index('idx_chunk_review_dept_class', table_name='document_chunks')
    op.drop_index('idx_chunk_go_num', table_name='document_chunks')
    op.drop_index('idx_chunk_embedding_hnsw', table_name='document_chunks', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index('idx_chunk_document_id', table_name='document_chunks')
    op.drop_index('idx_chunk_dept_class', table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index(op.f('ix_document_attributes_order_number'), table_name='document_attributes')
    op.drop_table('document_attributes')
    op.drop_index(op.f('ix_document_versions_sha256'), table_name='document_versions')
    op.drop_index('idx_doc_ver_source_url', table_name='document_versions')
    op.drop_index('idx_doc_ver_sha256', table_name='document_versions')
    op.drop_index('idx_doc_ver_retrieved_at', table_name='document_versions')
    op.drop_index('idx_doc_ver_document_id', table_name='document_versions')
    op.drop_table('document_versions')
    op.drop_table('access_grants')
    op.drop_index(op.f('ix_session_summaries_expires_at'), table_name='session_summaries')
    op.drop_table('session_summaries')
    op.drop_index('idx_prom_model', table_name='model_promotions')
    op.drop_index('idx_prom_date', table_name='model_promotions')
    op.drop_table('model_promotions')
    op.drop_index(op.f('ix_memberships_user_id'), table_name='memberships')
    op.drop_index(op.f('ix_memberships_organization_id'), table_name='memberships')
    op.drop_table('memberships')
    op.drop_table('ingestion_runs')
    op.drop_index(op.f('ix_ingestion_jobs_trace_id'), table_name='ingestion_jobs')
    op.drop_index(op.f('ix_ingestion_jobs_source_id'), table_name='ingestion_jobs')
    op.drop_index(op.f('ix_ingestion_jobs_idempotency_key'), table_name='ingestion_jobs')
    op.drop_table('ingestion_jobs')
    op.drop_table('documents')
    op.drop_index(op.f('ix_chat_turns_session_id'), table_name='chat_turns')
    op.drop_index('idx_turn_session_time', table_name='chat_turns')
    op.drop_table('chat_turns')
    op.drop_index(op.f('ix_api_keys_user_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_user_preferences_user_id'), table_name='user_preferences')
    op.drop_table('user_preferences')
    op.drop_table('sources')
    op.drop_index(op.f('ix_rag_triad_benchmarks_model_id'), table_name='rag_triad_benchmarks')
    op.drop_table('rag_triad_benchmarks')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index('idx_model_name_rev', table_name='model_artifacts')
    op.drop_index('idx_model_checksum', table_name='model_artifacts')
    op.drop_table('model_artifacts')
    op.drop_index(op.f('ix_idempotency_records_user_id'), table_name='idempotency_records')
    op.drop_index(op.f('ix_idempotency_records_expires_at'), table_name='idempotency_records')
    op.drop_table('idempotency_records')
    op.drop_index(op.f('ix_feedback_records_user_id'), table_name='feedback_records')
    op.drop_index(op.f('ix_feedback_records_trace_id'), table_name='feedback_records')
    op.drop_index(op.f('ix_feedback_records_session_id'), table_name='feedback_records')
    op.drop_index('idx_feedback_user', table_name='feedback_records')
    op.drop_index('idx_feedback_trace', table_name='feedback_records')
    op.drop_table('feedback_records')
    op.drop_index(op.f('ix_chat_sessions_user_id'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_expires_at'), table_name='chat_sessions')
    op.drop_index('idx_chat_user_exp', table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_index(op.f('ix_audit_events_sequence_num'), table_name='audit_events')
    op.drop_index('idx_audit_timestamp', table_name='audit_events')
    op.drop_index('idx_audit_seq', table_name='audit_events')
    op.drop_index('idx_audit_entity', table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_answer_reconstruction_audits_user_id'), table_name='answer_reconstruction_audits')
    op.drop_index(op.f('ix_answer_reconstruction_audits_trace_id'), table_name='answer_reconstruction_audits')
    op.drop_index(op.f('ix_answer_reconstruction_audits_session_id'), table_name='answer_reconstruction_audits')
    op.drop_index(op.f('ix_answer_reconstruction_audits_request_hash'), table_name='answer_reconstruction_audits')
    op.drop_index('idx_recon_trace', table_name='answer_reconstruction_audits')
    op.drop_index('idx_recon_req_hash', table_name='answer_reconstruction_audits')
    op.drop_table('answer_reconstruction_audits')
    op.drop_index(op.f('ix_agent_execution_audits_session_id'), table_name='agent_execution_audits')
    op.drop_index('idx_agent_user', table_name='agent_execution_audits')
    op.drop_index('idx_agent_session', table_name='agent_execution_audits')
    op.drop_index('idx_agent_date', table_name='agent_execution_audits')
    op.drop_table('agent_execution_audits')
    # ### end Alembic commands ###
